# Generated by Django 6.0.5 on 2026-05-28 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_cart_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('address', models.TextField()),
                ('payment_method', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.paint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.userregister')),
            ],
        ),
    ]
